<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="09_DbSelect.aspx.cs" Inherits="_02_componenti._09_DbSelect" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="dbc" runat="server"></asp:SqlDataSource>

            <asp:GridView ID="griSelect" runat="server"
                
                AutoGenerateSelectButton="true"
                AutoGenerateDeleteButton="true"
                DataKeyNames="Id"              
                OnSelectedIndexChanged="griSelect_SelectedIndexChanged"
                OnRowDeleting="griSelect_RowDeleting"
                ></asp:GridView>

           
             <asp:FormView ID="FormView1" runat="server">
                 <ItemTemplate>                     
                    
                     <fieldset>
                        <legend>Modifica utente</legend>                
                        <div>
                            <label for="txtNome">Nome</label>
                            <asp:TextBox ID="txtNome" runat="server" Text='<%# Eval("Nome") %>'></asp:TextBox>
                        </div>
                        <div>
                            <label for="txtNome">Cognome</label>
                            <asp:TextBox ID="txtCognome" runat="server" Text='<%# Eval("Cognome") %>'></asp:TextBox>
                        </div>
                        <div>
                            <label for="txtNome">Eta</label>
                            <asp:TextBox ID="txtEta" runat="server" Text='<%# Eval("Eta") %>'></asp:TextBox>
                        </div>
                        <div>
                            <label for="txtNome">Email</label>
                            <asp:TextBox ID="txtEmail" runat="server" Text='<%# Eval("Email") %>'></asp:TextBox>
                        </div>
                         <asp:Button ID="btnAggiorna" runat="server" OnClick="btnAggiorna_Click" Text="Aggiorna" />
                    </fieldset>

                 </ItemTemplate>    
             </asp:FormView>
            
        </div>
    </form>
</body>
</html>
